name: Off-chain

on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: cd off-chain && pip install -r requirements.txt

            - name: Lint Checker
              run: cd off-chain && poetry run lint

    test:
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: cd off-chain && pip install -r requirements.txt

            - name: Test off-chain
              run: cd off-chain && poetry run b
