name: Test

on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: cd marketplace-on-chain && yarn install -D

            - name: Format Checker
              run: cd marketplace-on-chain && yarn fmtc

    test:
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: cd marketplace-on-chain && yarn install -D

            - name: Compile Smart Contract
              run: cd marketplace-on-chain && yarn c

            - name: Test Smart Contract
              run: cd marketplace-on-chain && yarn t
