name: Test

on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: cd marketplace-off-chain && yarn install -D

            - name: Format Checker
              run: cd marketplace-off-chain && yarn fmtc

    test:
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: cd marketplace-off-chain && yarn install -D
              run: cd marketplace-on-chain && yarn install -D

            - name: Test on-chain
              run: cd marketplace-on-chain && yarn t

            - name: Test off-chain
              run: cd marketplace-off-chain && yarn t
